version: "3.8"

services:
  test:
    build:
      context: ../
      dockerfile: ./build/test/Dockerfile
    environment:
      SERVER_ADDR: http://server:7000
      PG_ADDR: postgres://user:1234@pg:5433/calendar
    networks:
      - calendar_test_net

networks:
  calendar_test_net:
    name: calendar_network
    external: true